# Site settings
title: Coding adventures
email: nomail
description: some things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alboletono
github_username:  alboletono

# Build settings
markdown: kramdown
