# Site settings
title: Coding adventures
email: nomail
description: Ô, pour me lire amoureusement cette belle page, avec un effort double je vais et guette.
baseurl: "/albinscode/" # the subpath of your site, e.g. /blog/
url: "http://albinweb.fr" # the base hostname & protocol for your site
twitter_username: alboletono
github_username:  alboletono

# Build settings
markdown: kramdown
